# Generated by Django 2.0.7 on 2018-07-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localgaap', '0002_auto_20180706_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='permanent_quota',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
    ]
