# Generated by Django 2.0.7 on 2018-07-08 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_version_copy_version'),
        ('localgaap', '0003_transaction_permanent_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deferred_tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Version')),
            ],
        ),
    ]
