# Generated by Django 2.0.7 on 2018-07-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_version_copy_version'),
        ('localgaap', '0004_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
