# Generated by Django 2.0.7 on 2018-07-08 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localgaap', '0005_auto_20180708_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Version'),
        ),
    ]
