# Generated by Django 2.0.7 on 2018-08-12 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localgaap', '0006_auto_20180708_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='deferred_tax_rate',
            field=models.DecimalField(decimal_places=6, default=0.32, max_digits=7),
        ),
        migrations.AlterField(
            model_name='setting',
            name='version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localgaap_setting', to='core.Version'),
        ),
    ]
