# Generated by Django 2.1 on 2018-08-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localgaap', '0007_auto_20180812_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localgaap_settings', to='core.Version'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.Version'),
        ),
    ]
