# Generated by Django 2.0.7 on 2018-07-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
