# Generated by Django 2.0.7 on 2018-08-12 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_version_copy_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.Company'),
        ),
        migrations.AlterField(
            model_name='version',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
